package repository

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/insider/league-api/internal/domain"
)

// FixtureRepo persists fixtures. Reads use the pool directly; writes
// take a pgx.Tx so they enrol in the caller's transaction.
type FixtureRepo struct {
	pool *pgxpool.Pool
}

func NewFixtureRepo(pool *pgxpool.Pool) *FixtureRepo {
	return &FixtureRepo{pool: pool}
}

var _ domain.FixtureRepository = (*FixtureRepo)(nil)

const selectFixtureColumns = `
	id, season_id, week, home_team_id, away_team_id,
	home_goals, away_goals, played, played_at
`

// ---------------------------------------------------------------------
// Reads
// ---------------------------------------------------------------------

func (r *FixtureRepo) GetByID(ctx context.Context, id int) (*domain.Fixture, error) {
	row := r.pool.QueryRow(ctx,
		`SELECT `+selectFixtureColumns+` FROM fixtures WHERE id = $1`,
		id,
	)
	f, err := scanFixture(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("fixture %d: %w", id, ErrNotFound)
		}
		return nil, fmt.Errorf("get fixture %d: %w", id, err)
	}
	return f, nil
}

func (r *FixtureRepo) GetBySeasonAndWeek(
	ctx context.Context,
	seasonID, week int,
) ([]domain.Fixture, error) {
	return r.queryFixtures(ctx,
		`SELECT `+selectFixtureColumns+`
		   FROM fixtures
		  WHERE season_id = $1 AND week = $2
		  ORDER BY id`,
		seasonID, week,
	)
}

func (r *FixtureRepo) GetBySeason(
	ctx context.Context,
	seasonID int,
) ([]domain.Fixture, error) {
	return r.queryFixtures(ctx,
		`SELECT `+selectFixtureColumns+`
		   FROM fixtures
		  WHERE season_id = $1
		  ORDER BY week, id`,
		seasonID,
	)
}

func (r *FixtureRepo) GetPlayed(
	ctx context.Context,
	seasonID int,
) ([]domain.Fixture, error) {
	return r.queryFixtures(ctx,
		`SELECT `+selectFixtureColumns+`
		   FROM fixtures
		  WHERE season_id = $1 AND played = TRUE
		  ORDER BY week, id`,
		seasonID,
	)
}

func (r *FixtureRepo) GetRemaining(
	ctx context.Context,
	seasonID int,
) ([]domain.Fixture, error) {
	return r.queryFixtures(ctx,
		`SELECT `+selectFixtureColumns+`
		   FROM fixtures
		  WHERE season_id = $1 AND played = FALSE
		  ORDER BY week, id`,
		seasonID,
	)
}

// ---------------------------------------------------------------------
// Writes
// ---------------------------------------------------------------------

func (r *FixtureRepo) Create(
	ctx context.Context,
	tx pgx.Tx,
	f *domain.Fixture,
) error {
	row := tx.QueryRow(ctx,
		`INSERT INTO fixtures
		    (season_id, week, home_team_id, away_team_id)
		 VALUES ($1, $2, $3, $4)
		 RETURNING id`,
		f.SeasonID, f.Week, f.HomeTeamID, f.AwayTeamID,
	)
	if err := row.Scan(&f.ID); err != nil {
		return fmt.Errorf("create fixture: %w", err)
	}
	return nil
}

func (r *FixtureRepo) Update(
	ctx context.Context,
	tx pgx.Tx,
	f *domain.Fixture,
) error {
	_, err := tx.Exec(ctx,
		`UPDATE fixtures
		    SET home_goals = $2,
		        away_goals = $3,
		        played     = $4,
		        played_at  = $5
		  WHERE id = $1`,
		f.ID, f.HomeGoals, f.AwayGoals, f.Played, f.PlayedAt,
	)
	if err != nil {
		return fmt.Errorf("update fixture %d: %w", f.ID, err)
	}
	return nil
}

// BulkCreate inserts all 12 fixtures generated by the scheduler in a
// single round-trip using pgx.Batch. Each fixture's ID is populated
// in-place so callers can reuse the slice for response payloads.
func (r *FixtureRepo) BulkCreate(
	ctx context.Context,
	tx pgx.Tx,
	fixtures []domain.Fixture,
) error {
	if len(fixtures) == 0 {
		return nil
	}
	batch := &pgx.Batch{}
	for _, f := range fixtures {
		batch.Queue(
			`INSERT INTO fixtures (season_id, week, home_team_id, away_team_id)
			 VALUES ($1, $2, $3, $4) RETURNING id`,
			f.SeasonID, f.Week, f.HomeTeamID, f.AwayTeamID,
		)
	}
	br := tx.SendBatch(ctx, batch)
	defer br.Close()

	for i := range fixtures {
		if err := br.QueryRow().Scan(&fixtures[i].ID); err != nil {
			return fmt.Errorf("bulk insert fixture %d: %w", i, err)
		}
	}
	return nil
}

// DeleteForSeason removes every fixture row for a season.
func (r *FixtureRepo) DeleteForSeason(
	ctx context.Context,
	tx pgx.Tx,
	seasonID int,
) error {
	if _, err := tx.Exec(ctx,
		`DELETE FROM fixtures WHERE season_id = $1`,
		seasonID,
	); err != nil {
		return fmt.Errorf("delete fixtures for season %d: %w", seasonID, err)
	}
	return nil
}

// LockForWeek selects the unplayed fixtures of a given week WITH
// row-level locks (FOR UPDATE) so concurrent SimulateWeek calls cannot
// double-play the same fixtures.
func (r *FixtureRepo) LockForWeek(
	ctx context.Context,
	tx pgx.Tx,
	seasonID, week int,
) ([]domain.Fixture, error) {
	rows, err := tx.Query(ctx,
		`SELECT `+selectFixtureColumns+`
		   FROM fixtures
		  WHERE season_id = $1 AND week = $2 AND played = FALSE
		  ORDER BY id
		  FOR UPDATE`,
		seasonID, week,
	)
	if err != nil {
		return nil, fmt.Errorf("lock fixtures for week %d: %w", week, err)
	}
	return collectFixtures(rows)
}

// LockByID selects a single fixture with FOR UPDATE.
func (r *FixtureRepo) LockByID(
	ctx context.Context,
	tx pgx.Tx,
	id int,
) (*domain.Fixture, error) {
	row := tx.QueryRow(ctx,
		`SELECT `+selectFixtureColumns+`
		   FROM fixtures
		  WHERE id = $1
		  FOR UPDATE`,
		id,
	)
	f, err := scanFixture(row)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, fmt.Errorf("fixture %d: %w", id, ErrNotFound)
		}
		return nil, fmt.Errorf("lock fixture %d: %w", id, err)
	}
	return f, nil
}

// ---------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------

func (r *FixtureRepo) queryFixtures(
	ctx context.Context,
	sql string,
	args ...any,
) ([]domain.Fixture, error) {
	rows, err := r.pool.Query(ctx, sql, args...)
	if err != nil {
		return nil, fmt.Errorf("query fixtures: %w", err)
	}
	return collectFixtures(rows)
}

func collectFixtures(rows pgx.Rows) ([]domain.Fixture, error) {
	defer rows.Close()
	var out []domain.Fixture
	for rows.Next() {
		f, err := scanFixture(rows)
		if err != nil {
			return nil, fmt.Errorf("scan fixture: %w", err)
		}
		out = append(out, *f)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate fixtures: %w", err)
	}
	return out, nil
}

func scanFixture(r rowScanner) (*domain.Fixture, error) {
	var f domain.Fixture
	if err := r.Scan(
		&f.ID, &f.SeasonID, &f.Week, &f.HomeTeamID, &f.AwayTeamID,
		&f.HomeGoals, &f.AwayGoals, &f.Played, &f.PlayedAt,
	); err != nil {
		return nil, err
	}
	return &f, nil
}
