// Package mocks provides hand-rolled, dependency-free fakes for every
// interface declared in internal/domain. The pattern is identical for
// every mock:
//
//   - Each method has a `<Method>Func` field. If non-nil, it is the
//     implementation used at call time.
//   - Each method increments a `<Method>Calls` counter so tests can
//     assert call counts.
//   - When `<Method>Func` is nil the method returns the zero value of
//     its return types so tests can ignore methods they don't care
//     about.
//
// This is intentionally not generated by mockery / gomock — the
// surface area is small enough that hand-rolled mocks are clearer
// than reading generated code in test failures.
package mocks
